### ISSUE TITLE
Longclaw with latest Wagtail and Django 3?

### ISSUE THREAD

**Issue by timparkin** [longclawshop/longclaw#368] opened 2021-03-14 12:25 UTC
# ISSUE\_TEMPLATE

* longclaw?
* Wagtail?
* Django3
* Python3

## Description

Can Longclaw be used with latest Wagtail and Django?

**Comment by janbaykara** [comment] 2022-06-23 16:19
Duplicate of #410

**Closed by janbaykara** 2022-06-23 16:19 UTC
